# Generated by Django 4.2.30 on 2026-05-18 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_completed', models.IntegerField(default=0)),
                ('quests_completed', models.IntegerField(default=0)),
                ('weekly_goals', models.IntegerField(default=0)),
                ('weekly_quests', models.IntegerField(default=0)),
                ('week_start', models.DateField(default=django.utils.timezone.now)),
                ('total_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
