# Generated by Django 4.2.30 on 2026-05-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_tier',
            field=models.IntegerField(default=0),
        ),
    ]
